import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingVertical: 60,
    paddingHorizontal: 16,
    backgroundColor: '#0F111A', 
  },
  title: {
    fontSize: 40,
    fontWeight: '900',
    marginBottom: 12,
    textAlign: 'center',
    color: '#FFB800', 
    fontFamily: 'Roboto',
    letterSpacing: 1,
  },
  description: {
    fontSize: 16,
    fontWeight: '400',
    marginBottom: 36,
    textAlign: 'center',
    color: '#D1D5DB', 
    fontFamily: 'Roboto',
    lineHeight: 24,
  },
  pyramidHeader: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  pyramidNameInput: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 6,
    borderBottomWidth: 2,
    borderBottomColor: '#FFB800', 
    paddingVertical: 8,
    width: 240,
    fontFamily: 'Roboto',
  },
  addLayerContainer: {
    marginTop: 16,
    alignSelf: 'center',
    backgroundColor: '#0e1320ff',
    paddingHorizontal: 26,
    paddingVertical: 14,
    borderRadius: 24,
    shadowColor: '#00000050',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
     borderColor: '#FFB800', 
    borderWidth: 1,
    elevation: 6,
  },
  addLayerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    
  },
  addLayerText: {
    color: '#ffffffff',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 12,
   
   
    fontFamily: 'Roboto',
  },
  pyramid: {
    flexDirection: 'column-reverse',
    alignItems: 'center',
    width: '100%',
    paddingBottom: 24,
  },
  layerRow: {
    width: '100%',
    alignItems: 'center',
    marginVertical: 6,
  },
  layer: {
    alignSelf: 'center',
    backgroundColor: '#1C1E2A',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 2,
    paddingHorizontal: 8,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.7,
    shadowRadius: 8,
    elevation: 8,
  },
  layerText: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 16,
    textAlign: 'left',
    fontFamily: 'Roboto',
    lineHeight: 24,
  },
  removeLayerBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 12,
  },
});
