import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingVertical: 60,
    paddingHorizontal: 15,
    backgroundColor: '#1a1a1a',
  },
  title: {
    fontSize: 36,
    fontWeight: '900',
    marginBottom: 8,
    textAlign: 'center',
    color: '#b0b0b0',
    fontFamily: 'Arial',
  },
  description: {
    fontSize: 14,
    fontWeight: '400',
    marginBottom: 20,
    textAlign: 'center',
    color: '#888888',
    fontFamily: 'Courier New',
  },
  pyramidHeader: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  pyramidNameInput: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#555555',
    paddingVertical: 4,
    width: 200,
  },
  addLayerContainer: {
    marginTop: 10,
    alignSelf: 'center',
    backgroundColor: '#2e2e2e',
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 4,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 6,
    elevation: 6,
  },
  addLayerRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  addLayerText: {
    color: '#aaaaaa',
    fontSize: 15,
    fontWeight: '700',
    marginLeft: 10,
  },
  pyramid: {
    flexDirection: 'column-reverse',
    alignItems: 'center',
    width: '100%',
    paddingBottom: 15,
  },
  layerRow: {
    width: '100%',
    alignItems: 'center',
    marginVertical: 4,
  },
  layer: {
    alignSelf: 'center',
    backgroundColor: '#3f3d3dff',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 2,
    paddingHorizontal: 8,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.7,
    shadowRadius: 8,
    elevation: 8,
  },
  layerText: {
    flex: 1,
    color: '#ffffffff',
    fontSize: 14,
    textAlign: 'center',
    paddingVertical: 10,
    fontFamily: 'Courier New',
    textAlignVertical: 'center',
    backgroundColor: 'transparent',
  },
  removeLayerBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 6,
  },
});
